### PR TITLE
styled this site with responsive design

### PR DESCRIPTION
**Pull request by Coderracharya**
Changes I've made :

- Optimized this site with responsive design
- Styled footer
- Created separate css file for developer's ease

### CODE REVIEW

**Comment by thatrobotdev** [comment]
OMG, THIS IS SO COOL! I love how it performs on small screen sizes! Unfortunately, the footer has been a frequently changed section, so there are now some conflicting edits between your footer and the footer as it exists on the page right now. Are you able to go in and merge your footer design with the new one, and resolve the conflict?

Let me know if you need any help with this process as well! GitHub makes it easy to resolve merge conflicts in the browser by clicking the "Resolve conflicts" button.

**Comment by ArijitAcharjee411** [comment]
I've resolved the conflicts in my pull request. Do you want any other changes that i should make then please mention that here.

**Comment by bear217** [comment]
Looks good, but this branch has some errors(?) that make it conflict with the base branch. If you could fix those it would be great and we should be able to merge it!

**Comment by ArijitAcharjee411** [comment]
> Looks good, but this branch has some errors(?) that make it conflict with the base branch. If you could fix those it would be great and we should be able to merge it!

hey @bear217, this is my first pull request so i don't have much idea about it. So, can you please help me to fix these issues ? 
It looks like the first conflict is with the CSS portion. I've created the CSS file separately and thereafter linked it inside the HTML file. Should i brought that style-sheet inside the HTML file ? Those CSS are the base which making the page responsive and the present design in the base branch isn't responsive at all.
Secondly, the footer in base branch is different from my design so kindly tell me if I've to change this.

**Comment by ArijitAcharjee411** [comment]
Yeah I'm working on it & will update here soon

**Pull request closed without merging**
