### PR TITLE
Update gallery.yml

### PR DESCRIPTION
**Pull request by ragmmangugn**
i think this works idk YAML is a language i don't know

# For Issue: #PLACE_ISSUE_NUMBER_HERE

## Fixes:
- sirui's name

## Additions:
- images of everyone's sprig projects (i hope)

# Checklist
- [ ] Ensured there is an open issue for your PR
- [ ] Added comments to additions
- [ ] Followed common formatting conventions for the contribution language
- [ ] Tested code to ensure original features are working

Select one:
- [ ] Ensured you are the contributer assigned to the Issue for this PR
- [ ] Commented for ownership of an OPEN issue where no one is assigned or has yet asked to be assigned

# Screenshots

### CODE REVIEW

**Comment by thatrobotdev** [comment]
Hey, good job adding yml for images! [gallery.html ](https://github.com/P2PHackClub/website/blob/main/gallery.html)would need to be updated to take in account the new data to be plopped into the page.

Currently, here's how the file works so far:

```html
---
layout: default
title: Site Gallery
---
```

This block is [Front Matter](https://jekyllrb.com/docs/front-matter/), which outlines the page's layout (currently `default`, utilizing [_layouts/default.html](https://github.com/P2PHackClub/website/blob/main/_layouts/default.html), and the page's title (which can later be accessed using `{{ page.title }}`

```html
<h2>{{ page.title }}</h2>

<p>Here, you can find projects made by P2P Hack Club members!</p>

<a href="/sprig">
    <h3>Sprig workshop (9/27/2022)</h3>
</a>
```
This is just standard HTML code, with that `{{ page.title }}` thrown in there to access the page title from the Front Matter for easy changes later.

```html
<ul>
    {% for item in site.data.gallery %}

    {% if item.workshop == "sprig" %}
    <li><a href="{{ item.link }}">"{{ item.name }}" by {{ item.author }}</a>
    </li>
    {% endif %}

    {% endfor %}
</ul>
```

Here's where the fun stuff begins! You'll notice some non-standard additions, starting with `{%` and ending with `%}` that defines some fun jekyll things. `{% for item in site.data.gallery %}` pulls the data from [_data/gallery.yml](https://github.com/P2PHackClub/website/blob/main/_data/gallery.yml) and makes it accessible with a variable called `item`.

The data is currently structured like: 
```yaml
- name: Sprig Game
  author: Ram M.
  workshop: sprig
  link: https://editor.sprig.hackclub.com/?id=038b386d5eb3059139f3f3800f16ada3
- name: ...
```

with each `-` denoting a new `item`, with each item having the accessible data points `name`, `author`, `workshop`, and `link`.

Within that for loop, HTML code will be repeated for each item.

The HTML Code above takes advantage of that by creating an unordered list `<ul>`, and creating a list item `<li>` if `item.workshop` is `sprig` (so that we can have multiple page sections later with different workshops. 

If you want to add your image, you can structure the YAML code like
```yaml
- name: Sprig Game
  author: Ram M.
  workshop: sprig
  link: https://editor.sprig.hackclub.com/?id=038b386d5eb3059139f3f3800f16ada3
  image_src: /assets/images/gallery/sprig/ram.png
- name: ...
```

with a new tag `image_src`, then access that data in the html with something like:
```html
<ul>
    {% for item in site.data.gallery %}

    {% if item.workshop == "sprig" %}
    <img src="{{ item.image_src }}" alt="Screenshot of {{ item.name }} by {{ item.author }}"
    <li><a href="{{ item.link }}">"{{ item.name }}" by {{ item.author }}</a>
    </li>
    {% endif %}

    {% endfor %}
</ul>
```

Hopefully this is helpful! If you can, can you update your commit to implement the images into the HTML code?

**Comment by ragmmangugn** [comment]
yes I will update my commit, thanks for the info, I had no idea what I was doing. I'll keep this in mind in the future.

**Comment by thatrobotdev** [comment]
Woooo! I think I'll eventually post a tutorial about how jekyll works somewhere in the README.md when I have the time. Thanks for tackling this, and let me know if you need any help!

**Comment by ragmmangugn** [comment]
Alright it's been updated now

**Comment by thatrobotdev** [comment]
Thank you!! 😁

**Pull request merged**
