### PR TITLE
Added a Styled navigation bar

### PR DESCRIPTION
**Pull request by user23ayush**
I have added a Navigation  bar . If anything needs to be changed kindly tell me else merge it.

### CODE REVIEW

**Comment by user23ayush** [comment]
I have styled the nav bar and pinned its image. If there is any conflict please tell else merge it.

**Comment by user23ayush** [comment]
Will it be merged?

**Comment by user23ayush** [comment]
I am working on it. If i will find the fix . I will pull request again else.

**Comment by S3cBar0n** [comment]
@user23ayush sounds good, ensure you check for any merges that need to happen with our main branch before requesting a new review.

I will keep an eye out for your updates.

**Pull request closed without merging**
