### PR TITLE
Add favicon

### PR DESCRIPTION
**Pull request by diamant3**
# For Issue: #55 

## Fixes:
- 

## Additions:
- add favicon

# Checklist
- [x] Ensured there is an open issue for your PR
- [x] Added comments to additions
- [x] Followed common formatting conventions for the contribution language
- [x] Tested code to ensure original features are working

Select one:
- [x] Ensured you are the contributer assigned to the Issue for this PR
- [x] Commented for ownership of an OPEN issue where no one is assigned or has yet asked to be assigned

# Screenshots
p2p_hack_club

### CODE REVIEW

**Review by thatrobotdev — CHANGES_REQUESTED** [review]
Thanks for the contribution! I was a little confused looking at it initially because although I saw your ico file, and the HTML changes looked correct, I wasn't seeing it in my browser! I then realized that safari is reeeaaaallly annoying when it comes to favicons: https://stackoverflow.com/questions/24992048/favicon-not-showing-in-safari.

Checking it in Chrome, it totally works though! I was wondering if you could use a tool like https://realfavicongenerator.net to add support for more browsers?

**Comment by diamant3** [comment]
Thanks!, ok i will do that.

**Comment by diamant3** [comment]
@thatrobotdev done!

**Comment by thatrobotdev** [comment]
Thank you so much, this looks great!

**Pull request merged**
