### PR TITLE
Add Under Construction Page

### PR DESCRIPTION
**Pull request by siddhantdixit**
Solves #12 

image

### CODE REVIEW

**Comment by S3cBar0n** [comment]
@siddhantdixit Looks fantastic!

I am reviewing the code, I will keep you updated.


Thanks!

**Comment by siddhantdixit** [comment]
@S3cBar0n hello! You're welcome! 
I want to have a conversation with you! Can I have your discord username? 🙃

**Comment by S3cBar0n** [comment]
@siddhantdixit send me your discord and I will add you.

**Comment by siddhantdixit** [comment]
> @siddhantdixit send me your discord and I will add you.

@S3cBar0n 
My Discord Username - 
Siddhant#5865

**Pull request merged**
